### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by syrakozz** [freekmurze/activitylog#7]
could you plz add a screenshots for the project, 
or link for the demo 
like pimpmylog project

**Comment by freekmurze** [comment]
Hi, 

if you follow the instructions of the README you can setup a demo yourself. Reading through the README should give you a good idea of the functionality this package provides.

**Comment by kykiskie** [comment]
hi sorry for this , i can use the Activity::log() just fine.

but im lost at log model events, can you please provide more literal examples.

lets say that i want to log the login action, how to do this ?

for now, i'm using Activity:log() in every function that i want to log, but it seems tiring, and log model events is far cleaner if i'm able to implement it.

cheers

**Comment by freekmurze** [comment]
If you want to log a user logging in that you put  `Activity::log()` somewhere in the controller that performs the login.

You can hook into model events by letting models implement `LogsActivityInterface`. See the readme for more details.
